deploys:
  # The hostname
  sl.infinitybots.gg:
    # The URL with protocol
    url: "https://sl.infinitybots.gg"
    # The service description
    description: Server Listing Experiment. Needs admin+
    # The permissions needed for the service
    perms:
      - admin
    # Whether the service is enabled for viewing
    enabled: true
    # The host to proxy to
    to: http://localhost:30008
  sl-api.infinitybots.gg:
    url: "https://sl-api.infinitybots.gg"
    description: Server Listing Experiment API
    enabled: true
    to: http://localhost:30009
    bypass:
      ends_with:
        - /seo
    mfa: true  
  sysmanage.infinitybots.gg:
    url: "https://sysmanage.infinitybots.gg"
    description: System Management
    enabled: true
    mfa: true
    to: http://localhost:30010
    allowed_ids:
      - 510065483693817867
      - 728871946456137770
    strict: true # Strict means that the permissive allowlist is ignored
  helpernode-metro.infinitybots.gg:
    url: "https://helpernode-metro.infinitybots.gg"
    description: Metro Helper Node System Management
    enabled: true
    to: http://100.104.199.117:30010
    allowed_ids:
      - 510065483693817867
      - 728871946456137770
    strict: true # Strict means that the permissive allowlist is ignored
  vivum.botlist.app:
    url: "https://vivum.botlist.app"
    description: Vivum Internal Infrastructure. You must be in a department to access this.
    enabled: true
    to: http://localhost:49104
    strict: true # Strict means that the permissive allowlist is ignored
    hide_login_html: false

perms:
  owner: "SELECT owner FROM users WHERE user_id = $1"
  admin: "SELECT admin FROM users WHERE user_id = $1"

port: 1234