deploys:
  sl.infinitybots.gg:
    url: "https://sl.infinitybots.gg"
    github_repo: "InfinityBotList/Infinity-Next"
    github_ref: "refs/heads/priv-serverlist"
    description: Server Listing Experiment. Needs admin+
    perms:
      - admin
    enabled: true
    to: http://localhost:30008