deploys:
  sl.infinitybots.gg:
    url: "https://sl.infinitybots.gg"
    git:
      github_repo: "InfinityBotList/Infinity-Next"
      path: /root/priv-sl
      github_ref: "refs/heads/priv-serverlist"
      service: "priv-sl"
    description: Server Listing Experiment. Needs admin+
    perms:
      - admin
    enabled: true
    to: http://localhost:30008