deploys:
  system.purrquinox.com:
    url: "https://system.purrquinox.com"
    description: Hello, there. This is a Internal System Resources Manager for Purrquinox and our services!
    enabled: true
    mfa: true
    to: http://localhost:29393
    allowed_ids:
      - 564164277251080208
      - 728871946456137770
      - 775855009421066262
    strict: true # Strict means that the permissive allowlist is ignored
  splashtail-sec.antiraid.xyz:
    url: "https://splashtail-sec.antiraid.xyz"
    description: "Secure access to splashtail mewld etc."
    enabled: true
    mfa: true
    to: http://localhost:5600
    allowed_ids:
      - 564164277251080208
      - 728871946456137770
      - 775855009421066262
    strict: true # Strict means that the permissive allowlist is ignored
  staffapi-s3.antiraid.xyz:
    url: "https://staffapi-s3.antiraid.xyz"
    description: "S3 file viewer"
    enabled: true
    mfa: true
    to: http://localhost:8334
    strict: true
    allowed_ids:
      # Highly sensitive, even compared to other staffapi functions
      - 564164277251080208
      - 728871946456137770
      - 775855009421066262

perms:
  owner: "SELECT owner FROM users WHERE user_id = $1"
  admin: "SELECT admin FROM users WHERE user_id = $1"

port: 1234
